site_name: geogee
site_description: A Python package for geospatial analysis
site_author: Ly Mot
site_url: https://lymot.github.io/geogee
repo_url: https://github.com/LyMot/geogee

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
  - mkdocs-jupyter:
      include_source: true
      execute: false
      allow_errors: true





markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - Report Issues: https://github.com/geogee/geogee/issues
  - API Reference:
      - common module: common.md
      - geogee module: geogee.md
      - utils module: utils.md
  - Notebooks:
      - ipyleaflet intro: notebooks/ipyleaflet_intro.ipynb
      - folium intro: notebooks/Folium_intro.ipynb
      - geogee intro: notebooks/geogee_intro.ipynb
      - add_shapefile: notebooks/add_shapefile.ipynb
      - test_utils: notebooks/test_utils.ipynb

